language: node_js
node_js:
- 6.10.0
after_script:
- scp -o StrictHostKeyChecking=no ./app.js yana:/root/travistest
before_install:
- openssl aes-256-cbc -K $encrypted_fa7fc7697281_key -iv $encrypted_fa7fc7697281_iv
  -in id.enc -out id -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
