language: node_js
node_js:
- 9.10.1
after_script:
- scp -o StrictHostKeyChecking=no ./app.js yana:/root/travistest
before_install:
- openssl aes-256-cbc -K $encrypted_fa7fc7697281_key -iv $encrypted_fa7fc7697281_iv
  -in yana_rsa.enc -out yana_rsa -d
- mv yana_rsa ~/.ssh -f
- chmod 600 ~/.ssh/yana_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/yana_rsa
- cp .travis/ssh_config ~/.ssh/config
